### ISSUE TITLE
node version mismatch?

### ISSUE THREAD

**Issue by kouohhashi** [orbitdb/orbit-db#270]
Hi,
Maybe because i'm a newbie to orbit-db and ipfs,
but I can not execute even simplest scripts.

If I tried ipfs-api, I got ...
```
const IpfsApi = require('ipfs-api')
const OrbitDB = require('orbit-db')
const ipfs = IpfsApi('localhost', '5001')
const orbitdb = new OrbitDB(ipfs)
orbitdb.log('hello')

TypeError: db3.iterator is not a function
```

if i tried no api version, I got ...
```
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

// OrbitDB uses Pubsub which is an experimental feature
// and need to be turned on manually. 
// Note that these options need to be passed to IPFS in 
// all examples in this document even if not specfied so.
const ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  },
}

// Create IPFS instance
const ipfs = new IPFS(ipfsOptions)

ipfs.on('ready', () => {
  // Create OrbitDB instance
  const orbitdb = new OrbitDB(ipfs)
})


Error: version mismatch: expected v6, found v5
    at get (/home/kouohhashi/loancoin_oracle/node_modules/ipfs-repo/src/version.js:57:27)
    at store.get (/home/kouohhashi/loancoin_oracle/node_modules/ipfs-repo/src/version.js:31:9)
    at /home/kouohhashi/loancoin_oracle/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

My node version is v8.9.2
"ipfs": "^0.27.0",  
"ipfs-api": "^17.2.4",  
"orbit-db": "^0.18.7",  

Could you give me a hint?

Thanks in advance.

**Comment by haadcode** [comment]
Thanks @kouohhashi for reporting the issue!

The version mismatch, `Error: version mismatch: expected v6, found v5`, is due to the IPFS data repository (directory), see here for more details https://github.com/ipfs/js-ipfs/issues/1071. That means that the existing IPFS directory needs to be migrated to the new version. To go around this, I usually just use another directory for IPFS:
```javascript
const ipfsOptions = {
  repo: './path/to/another/dir',
  EXPERIMENTAL: {
    pubsub: true
  },
}
```

Regarding `ipfs-api`, we haven't supported ipfs-api in a few months so it's not guaranteed to work unfortunately :/ It's been requested by other people too so I opened an issue to track the progress here https://github.com/orbitdb/orbit-db/issues/273.

**Comment by kouohhashi** [comment]
It works. Thanks!
