### ISSUE TITLE
Unable to replicate a db from its address (Chrome, orbit-db@0.18.10, ipfs@0.27.4)

### ISSUE THREAD

**Issue by cristiano-belloni** [orbitdb/orbit-db#285]
Hi,

In one instance of my app I have a user creating a feed and sharing the feed's address.
In another instance (another browser), I have a user importing the address manually and trying to replicate the feed. The issue I'm experiencing at the moment is that the feed is never replicated and waits indefinitely:

    // This never returns
    const feedDb = await orbitdb.feed(address)

Please note that I'm trying this with `orbit-db@0.18.10`, because of https://github.com/orbitdb/orbit-db/issues/280, on Chrome. If it's a known bug that should disappear with a newest version, I'll just wait for #280 to be closed.

Also note that I *was* able to replicate databases with the same code. The last version I had working was `orbit-db@0.18.3`.

**Comment by haadcode** [comment]
@cristiano-belloni this should be fixed in master now. I haven't done a release yet as I want to get some testing in and pull in the fix for the browser import problem before doing so. If you have time to check your app with master and let us know if you're still experiencing the problems, that'd be hugely helpful!

**Comment by cristiano-belloni** [comment]
@haadcode Thanks! I'm currently travelling across Europe but will take a look as soon as I can.
