### ISSUE TITLE
OrbitDB p2p failed on Google Cloud VM Ubuntu16.04 with 2 VM 

### ISSUE THREAD

**Issue by dexterchan** [orbitdb/orbit-db#295]
HI
I was able to run the orbit db in Ubuntu 16.04.... but failed to make 2VM Peer to Peer working.
Please find the attachment.

My first node is run with firstOrbitDbHost.js with internal IP 10.128.0.3 
From netstat, the program is listening to 4002 and 4003.... I enabled firewall for those ports.
firstOrbitDbHost only create a keystore db and insert value pair of name - hello
hosted with address:
/orbitdb/QmcswCMgT6qrDtpCRUZGVdcFy7n6Ax2cMcRTiUaBgSQpBK/first-database

Then, I run the second PeerOrbitDb.js in another vm with internal IP 10.128.0.4
It open the DB with 
const db = await orbitdb.keyvalue("/orbitdb/QmcswCMgT6qrDtpCRUZGVdcFy7n6Ax2cMcRTiUaBgSQpBK/first-database")

However, from the log, PeerOrbitDb only listen to
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmU8xnHDiRJ3tGvRS3d3LxLNZXNmUjSwiHGziwobA7BKrJ
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmU8xnHDiRJ3tGvRS3d3LxLNZXNmUjSwiHGziwobA7BKrJ
Swarm listening on /ip4/10.128.0.4/tcp/4002/ipfs/QmU8xnHDiRJ3tGvRS3d3LxLNZXNmUjSwiHGziwobA7BKrJ

But not 10.128.0.3....

The 2 VM run local independently.... Is there something wrong with my API call?
I expect the PeerOrbitDb run the data extraction after replication completed.
But, replicated event never appear......

[Archive 2.zip](https://github.com/orbitdb/orbit-db/files/1594164/Archive.2.zip)

**Comment by dexterchan** [comment]
read the IPFS doc: https://github.com/ipfs/ipfs-mans/blob/master/doc-src/ipfs/daemon.yaml
is there any way to configure orbit-db to broadcast as 0.0.0.0 ?

**Comment by haadcode** [comment]
I believe this is possible by setting the IPFS config to use 0.0.0.0 as the address:
```
    config: {
      Addresses: {
        API: '/ip4/127.0.0.1/tcp/0',
        Swarm: ['/ip4/0.0.0.0/tcp/0'],
        Gateway: '/ip4/0.0.0.0/tcp/0'
      },
```

Note that `/0` means "start in random port", replace it with your desired port if a static port is needed.

Let me know if that helped!

**Comment by dexterchan** [comment]
I modified
const ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  },
  Addresses: {
        API: '/ip4/127.0.0.1/tcp/4001',
        Swarm: ['/ip4/0.0.0.0/tcp/4002'],
        Gateway: '/ip4/0.0.0.0/tcp/4003'
  },
}

and feed into 
// Create IPFS instance
const ipfs = new IPFS(ipfsOptions)

However, still not working as expected
"PeerOrbitDb.js" still not receive the replicated events....
I updated "Archive 2.zip" as attached.
[Archive 2.zip](https://github.com/orbitdb/orbit-db/files/1595781/Archive.2.zip)

**Comment by nillia** [comment]
@dexterchan, I saw your code and I notice you don't pass the address inside the config as the specs. 
However, still not working because the peer is unable to connect to the DB owner with the default address.

If you change the Swarm address (extracted from examples) as below its working:
```javascript
    config: {
      Addresses: {
        API: '/ip4/127.0.0.1/tcp/0',
        Swarm: ['/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star'],
        Gateway: '/ip4/0.0.0.0/tcp/0'
      }
```

I attach your code with my modifications: [example.zip](https://github.com/orbitdb/orbit-db/files/1596420/example.zip)

@haadcode, Do you know why this is working but not in local?

**Comment by dexterchan** [comment]
Does "'/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star'" mean I need to use port 443?
Do I need to open port 443?

When running in the another VM, I have not got 
_get entries...
hello_

here is the log output, I modified the DB address 
"/orbitdb/QmcswCMgT6qrDtpCRUZGVdcFy7n6Ax2cMcRTiUaBgSQpBK/first-database"
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmU8xnHDiRJ3tGvRS3d3LxLNZXNmUjSwiHGziwobA7BKrJ
Connecting to database
DB address:/orbitdb/QmcswCMgT6qrDtpCRUZGVdcFy7n6Ax2cMcRTiUaBgSQpBK/first-database
DB keypair:
[object Object]
DB public key:
040d0752064316eed8e382155b6cbfb45c4de63db2460f987dffcf50bdcc9aaef958e99ee02c8e6efe60fc5e73cdfeef6630d82b8605884dd7b7332e51f88e3b10

**Comment by dexterchan** [comment]
For both VM  443 port can be connected:
with command:
lsof -i:443

Here is the example from one of the VM
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    13150 dexter   17u  IPv4  93014      0t0  TCP ipfs2.c.dextergcptest1.internal:38564->188.166.203.82:https (ESTABLISHED)
node    13150 dexter   23u  IPv4  93217      0t0  TCP ipfs2.c.dextergcptest1.internal:47888->chappy.i.ipfs.io:https (ESTABLISHED)
node    13150 dexter   24u  IPv4  93050      0t0  TCP ipfs2.c.dextergcptest1.internal:56134->scrappy.i.ipfs.io:https (ESTABLISHED)

**Comment by nillia** [comment]
> Does "'/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star'" mean I need to use port 443?

Yes, I suggested change the method because both nodes are not discovering each other. The other thing you can try is the discovery by mDNS which only works in local networks.

> COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
node 13150 dexter 17u IPv4 93014 0t0 TCP ipfs2.c.dextergcptest1.internal:38564
 188.166.203.82:https (ESTABLISHED)

Apparently both are connected to the Rendezvous Server of [https://github.com/libp2p/js-libp2p-websocket-star](url) (The IP 188.166.203.82).

Did you try my examples? I had this working (the code inside example.zip) with two instances of GCP in a new project. The second example (example_local) works in 2 VM in my computer but not in CGP.

One of my modifications, besides the config, is change the method who connect the db in PeerOrbitDb.js from:
```javascript
const db = await orbitdb.keyvalue(remoteDB)
```
to
```javascript
const db = await orbitdb.open(remoteDB)
```

**Comment by dexterchan** [comment]
Thanks for your reminder. I overlooked the change in PeerOrbitDb.js...
I tried the PeerOrbitDb.js again... but, sth is still missing...
I downloaded your package example.zip...

In VM1, running firstOrbitDbHost.js, I got
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmU8xnHDiRJ3tGvRS3d3LxLNZXNmUjSwiHGziwobA7BKrJ
DB address:/orbitdb/QmdesBhfvxFPN1PnFis6RqisfNeGDs8zNc1eWmDv2QBG3L/first-database
DB keypair:
[object Object]
DB public key:
049071c3a1ad98fd74b04d90259464cf8d8d2d35ca8c48f0e06bfa79605cc975beb2bd56ee1b05247581e88fcd72b350dea375c814138e283912b91c59566de46f
try insert entries....
get entries...
hello

from lsof -i:443, seem we connected to Rendezvous server
node    3717 dexter   17u  IPv4  25293      0t0  TCP ipfs.c.dextergcptest1.internal:43240->188.166.203.82:https (ESTABLISHED)
node    3717 dexter   23u  IPv4  25354      0t0  TCP ipfs.c.dextergcptest1.internal:57484->chappy.i.ipfs.io:https (ESTABLISHED)
node    3717 dexter   24u  IPv4  25355      0t0  TCP ipfs.c.dextergcptest1.internal:39760->scrappy.i.ipfs.io:https (ESTABLISHED)
dexter@ipfs:~$ 

IN VM2, we run PeerOrbitDb.js, replace 
remoteDB = '/orbitdb/QmdesBhfvxFPN1PnFis6RqisfNeGDs8zNc1eWmDv2QBG3L/first-database'
which is my DB address in VM1....
Executing it, I got stuck at
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmU8xnHDiRJ3tGvRS3d3LxLNZXNmUjSwiHGziwobA7BKrJ
Connecting to database
From lsof -i:443, it is connected to the Rendezvous server
node    3792 dexter   17u  IPv4  25918      0t0  TCP ipfs2.c.dextergcptest1.internal:55852->188.166.203.82:https (ESTABLISHED)
node    3792 dexter   23u  IPv4  25945      0t0  TCP ipfs2.c.dextergcptest1.internal:50016->chappy.i.ipfs.io:https (ESTABLISHED)
node    3792 dexter   24u  IPv4  25943      0t0  TCP ipfs2.c.dextergcptest1.internal:47318->scrappy.i.ipfs.io:https (ESTABLISHED)

In long term, I would like to implement a IPFS powered database to share record of multiple instances of Mongo scattering in different cloud region and server in premise....
It is the reason I used GCP VM to proof the concept of orbitdb...

Is there any log I can read further?
For server setup , I applied 
npm install orbit-db ipfs
to setup my vm for testing under Ubuntu 16.04

I have attached my latest modified example from yours at here:
[Archive.zip](https://github.com/orbitdb/orbit-db/files/1600764/Archive.zip)

Thank you very much and wish you a successful year!

**Comment by haadcode** [comment]
@dexterchan sorry to hear you're having troubles! :( 

I downloaded your latest code, ran as per your instructions and it seems to be working. I'm getting the following output:
```
$  node firstOrbitDbHost.js
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmeKvcr6F89jkLWEqsd8QnH4sYRRvfwDGNykAi1GmEBgQS
DB address:/orbitdb/QmS5KeJGHRgJUrPhMhqaMnTLcoPMv7iBnPgdFyox8y6LdM/first-database
DB keypair:
[object Object]
DB public key:
04ccebfbb7ce42ab36adf329cb42bfb8e9d1a2b96c98d289f9a5b2c6e7c2617f45aaa7903d07a6a35dd581da2f573d462ba15ce0e6890aefc5fe1ac40ae74b71e0
try insert entries....
get entries...
hello
```
And running the second peer (in another directory to make sure both have unique local data dir):
```
$ node PeerOrbitDb.js
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmYHExHtTzFEjdwyQcJkD9gaKKgfwvGswoFb4simrJn5Q6
Connecting to database
Database connected to/orbitdb/QmS5KeJGHRgJUrPhMhqaMnTLcoPMv7iBnPgdFyox8y6LdM/first-database
DB address:/orbitdb/QmS5KeJGHRgJUrPhMhqaMnTLcoPMv7iBnPgdFyox8y6LdM/first-database
DB keypair:
[object Object]
DB public key:
04dfadf4f9c6e149564451f9c3f8bd242aca1693483700446ecd08f7d1121ab325a8e71104b6c6a790dc211a1f71006142c77432ee3ef5430e0db4a20f26e723b4
get entries...
hello
```
*(I also tried it with db.keyvalue() instead of db.open(), the .keyvalue() should work the same as open)*

It looks like you're doing everything correctly from the code perspective, so I'm not quite sure why it isn't working on your VMs. I'm running on OSX and you seem to be on Ubuntu, so that *might have* something to do with it (although it shouldn't).

What you can do to check if peers are indeed connected, is to run both with `LOG=debug node youfile.js` which will output debug logging for OrbitDB. There's an internal `_onPeerConnected` method which will [output](https://github.com/orbitdb/orbit-db/blob/master/src/OrbitDB.js#L144) upon new peers. You should see `New peer '${peer}' connected to '${address}'` on both nodes. Perhaps that will help to narrow down whether this is an issue with OrbitDB or with connectivity.

Another check you can do, is to check if the peers are connected on IPFS swarm level (the above is if they're connected on IPFS Pubsub level and to the same database) by checking the peers using: https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/SWARM.md#peers. Add it somewhere in your code after `ipfs.on('ready')` and perhaps call it at an interval so that you see if the nodes connect.

If both fail, as in if you don't see the peers connected, then I would think it's a connection problem between the nodes. If you see peers in IPFS swarm but not in OrbitDB debug log, then it's something with OrbitDB (or its dependencies). In any case, please do let us know your findings! Let's figure this out for you and get it working 😄👍

And thank you @nillia for helping out! ❤️

**Comment by nillia** [comment]
> Thank you very much and wish you a successful year!

Thanks, have a great year you too!


>Is there any log I can read further?

You can access to Orbit log with: 
```javascript
const OrbitDB = require('orbit-db')
const Logger = require('logplease');
Logger.setLogLevel('DEBUG')
```

Its seems to be a problem with your settings because I ran your code in my machines and its working. 
My deps are:
```json
  "dependencies": {
    "ipfs": "^0.27.5",
    "orbit-db": "^0.19.0"
  }
```

Here is the log working so you can compare with yours.

```
-> node firstOrbitDbHost.js
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmaQwfW5uFVi6Bzn5kyJLk16K5bnAA38zYEnzwzAVoRBH8
2018-01-03T16:29:39.066Z [DEBUG] orbit-db: open()
2018-01-03T16:29:39.067Z [DEBUG] orbit-db: Open database 'first-database'
2018-01-03T16:29:39.067Z [DEBUG] orbit-db: Look from './orbitdb'
2018-01-03T16:29:39.068Z [WARN]  orbit-db: Not a valid OrbitDB address 'first-database', creating the database
2018-01-03T16:29:39.069Z [DEBUG] orbit-db: create()
2018-01-03T16:29:39.069Z [DEBUG] orbit-db: Creating database 'first-database' as keyvalue in './orbitdb'
2018-01-03T16:29:39.098Z [DEBUG] orbit-db: Saved manifest to IPFS as 'QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC'
2018-01-03T16:29:39.099Z [DEBUG] orbit-db: Created database '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database'
2018-01-03T16:29:39.099Z [DEBUG] orbit-db: open()
2018-01-03T16:29:39.100Z [DEBUG] orbit-db: Open database '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database'
2018-01-03T16:29:39.100Z [DEBUG] orbit-db: Look from './orbitdb'
2018-01-03T16:29:39.101Z [DEBUG] orbit-db: Found database '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database'
2018-01-03T16:29:39.101Z [DEBUG] orbit-db: Loading Manifest for '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database'
2018-01-03T16:29:39.102Z [DEBUG] orbit-db: Manifest for '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database':
{
  "name": "first-database",
  "type": "keyvalue",
  "accessController": "/ipfs/QmNytodcV7Zim6kAxtR8dzJMumxPm28mheHbHsY1Um1ckE"
}
2018-01-03T16:29:39.104Z [DEBUG] orbit-db: Saved manifest to IPFS as 'QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC'
DB address:/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database
DB keypair:
[object Object]
DB public key:
0400249dc2e54b40407a126601d3672b2a1a0b724e83302be6b2736c37618c31903535bbe7cffd0e5de2749baefcb9c0961ccaa682bf056863f4291be047f7274b
try insert entries....
2018-01-03T16:29:39.128Z [DEBUG] orbit-db.ipfs-pubsub: Topics open: 1
get entries...
hello
2018-01-03T16:31:07.132Z [DEBUG] orbit-db.ipfs-pubsub: Peer connected: /orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database true
2018-01-03T16:31:07.133Z [DEBUG] orbit-db: New peer 'QmZaRFUHs6DM1x4kkmSjRLJSNK5mG75wpKxnGMfJT28RDQ' connected to '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database'
2018-01-03T16:31:07.134Z [DEBUG] orbit-db: Send latest heads of '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database':
 [
  "QmT2FgyCXwCk89tz5tcjtqUhUYN93HY1i1Ea2P8MJLV9HV"
]
```

```log
-> node PeerOrbitDb.js
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmZaRFUHs6DM1x4kkmSjRLJSNK5mG75wpKxnGMfJT28RDQ
Connecting to database
2018-01-03T16:30:58.284Z [DEBUG] orbit-db: open()
2018-01-03T16:30:58.284Z [DEBUG] orbit-db: Open database '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database'
2018-01-03T16:30:58.284Z [DEBUG] orbit-db: Look from './orbitdb'
2018-01-03T16:30:58.290Z [DEBUG] orbit-db: Didn't find database '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database'
2018-01-03T16:30:58.290Z [DEBUG] orbit-db: Loading Manifest for '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database'
2018-01-03T16:31:03.672Z [DEBUG] orbit-db: Manifest for '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database':
{
  "name": "first-database",
  "type": "keyvalue",
  "accessController": "/ipfs/QmNytodcV7Zim6kAxtR8dzJMumxPm28mheHbHsY1Um1ckE"
}
2018-01-03T16:31:03.673Z [DEBUG] orbit-db: Saved manifest to IPFS as 'QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC'
Database connected to/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database
DB address:/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database
DB keypair:
[object Object]
DB public key:
04ea617d6c1a50deed783bc7df91683ac22c29199064218061fbadbba888f48a303957a22a09f14134690c86263098cb3d1290109ed1f98c03ad04c0212f4440cb
2018-01-03T16:31:06.850Z [DEBUG] orbit-db.ipfs-pubsub: Topics open: 1
2018-01-03T16:31:07.853Z [DEBUG] orbit-db.ipfs-pubsub: Peer connected: /orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database true
2018-01-03T16:31:07.853Z [DEBUG] orbit-db: New peer 'QmaQwfW5uFVi6Bzn5kyJLk16K5bnAA38zYEnzwzAVoRBH8' connected to '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database'
2018-01-03T16:31:08.048Z [DEBUG] orbit-db: Received 1 heads for '/orbitdb/QmYzf8EwdpauZJNRgCksMNPjiFUSC1PERUXj8tPFmbT4ZC/first-database':
 [
  "QmT2FgyCXwCk89tz5tcjtqUhUYN93HY1i1Ea2P8MJLV9HV"
]
2018-01-03T16:31:08.048Z [DEBUG] orbit-db.store: Sync request #1 1
2018-01-03T16:31:08.065Z [DEBUG] orbit-db.store: Saved heads 1 [QmT2FgyCXwCk89tz5tcjtqUhUYN93HY1i1Ea2P8MJLV9HV]
get entries...
hello
```

**Comment by dexterchan** [comment]
HI
After two days of trial.... I got it successful 2 times out of 4 trials.

IN the end, I got it working with
1) brand new Debian 9 VM on GCP (Google Cloud Platform)
2) first node in MacOS 10.13.2; second node in one Debian 9 VM in GCP; third Debian 9 VM in GCP failed

IN my impression, it sometimes work but not very stable. I attached my final source code in this post.
Is there anyway that we can improve stability? :)

Snapshot of first node on my MAC:
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmU7YSqsVtGizeYVULgAdykybuU5FHRoTRmDHuR59J2ctL
DB address:/orbitdb/QmTfvpfWwXiUhJof8nHX5aNJxfGBKndcqekYojrNjC74ph/first-database
DB keypair:
[object Object]
DB public key:
04b2dc20e5d2232d1ad5fbe959c99a2d112b8c39acd4e5ebc51303a5ae2e6b364311f6e0f564742aebe529ba3a5528c97c4458d7aea0132e6d462d738b00a07713
try insert entries....
get entries...
hello

Node in my DEbian VM on GCP
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmZ6uRvk8XbJAM462xyrgcn5NiNEicnhfNzkP1LCmnj1cz
Connecting to database
Database connected to/orbitdb/QmTfvpfWwXiUhJof8nHX5aNJxfGBKndcqekYojrNjC74ph/first-database
DB address:/orbitdb/QmTfvpfWwXiUhJof8nHX5aNJxfGBKndcqekYojrNjC74ph/first-database
DB keypair:
[object Object]
DB public key:
04040d26f8c76d27499b8140ddc72abaf3badfc2868c13cde1ce398fdb2e9c11e65b3dcb18dbc4eb1ac9a1a856e9b9941f3c1728eda2bee9417e30d919f6b240cc
get entries...
hello

third Debian on GCP failed
It failed to get any swarm peers
warm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmZ6uRvk8XbJAM462xyrgcn5NiNEicnhfNzkP1LCmnj1cz
Connecting to database
Database connected to/orbitdb/QmTfvpfWwXiUhJof8nHX5aNJxfGBKndcqekYojrNjC74ph/first-database
DB address:/orbitdb/QmTfvpfWwXiUhJof8nHX5aNJxfGBKndcqekYojrNjC74ph/first-database
DB keypair:
[object Object]
DB public key:
04040d26f8c76d27499b8140ddc72abaf3badfc2868c13cde1ce398fdb2e9c11e65b3dcb18dbc4eb1ac9a1a856e9b9941f3c1728eda2bee9417e30d919f6b240cc
[]
Error: MAC Invalid: 939cf6b91537e615067565ad5f0fa1ceb25623e978056c9d7a71441fc62394df != 727e9c2e6cc293b5bafcebd2b010e0d5b3a4a01e14eb9c622c6f891b2c981edc
    at mac.digest (/home/dexter/IPFS_DB/node_modules/libp2p-secio/src/etm.js:5



[Archive.zip](https://github.com/orbitdb/orbit-db/files/1608623/Archive.zip)

**Comment by haadcode** [comment]
Glad to hear you got it working to some extent!

> IN my impression, it sometimes work but not very stable. I attached my final source code in this post. Is there anyway that we can improve stability? :)

I believe this is not an issue of stability. There's something in the logs that gives us a clue:

> Node in my DEbian VM on GCP
> ...
> Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmZ6uRvk8XbJAM462xyrgcn5NiNEicnhfNzkP1LCmnj1cz

And

> third Debian on GCP failed
> ...
> Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmZ6uRvk8XbJAM462xyrgcn5NiNEicnhfNzkP1LCmnj1cz

It looks to me that the second and third node (the Debian ones) are, for some reason, the same IPFS node, ie. they have the same peer ID. IPFS doesn't support having the same peer ID on two separate nodes nor processes, they should always be unique. I believe this is the root cause of the issues you're seeing in connectivity.

How do you setup the VMs? Are they using the same IPFS data directory or the same config file? Perhaps reading from the same file system? If so, that could very well be the reason.

Try setting up the third VM so that it is *unique* in that they don't share the filesystem or any other resources. If you need to run it on the same filesystem, but in two separate processes, you can point IPFS to use a specific directory by adding an ENV variable: `IPFS_PATH=/path/to/another/directory node program.js`. Same applies for OrbitDB, it needs to use a unique directory per instance. You can also configure IPFS to use another directory programmatically, see [here](https://github.com/orbitdb/orbit-db/blob/master/examples/eventlog.js#L11), and OrbitDB [here](https://github.com/orbitdb/orbit-db/blob/master/examples/eventlog.js#L24) (the second argument).

Hope this helps! I'll re-open the issue so that we can make sure you got it working as expected. Feel free to close it if above does the trick! 😃

**Comment by haadcode** [comment]
@dexterchan were you able to get it working as expected?

**Comment by dexterchan** [comment]
HI, I am going to try this in the weekend. thanks!

**Comment by dexterchan** [comment]
Hi haadcode
Previously, my testing process is
1) setup the server with node.js and orbitdb lib in a directory, say "ipfs"
After setup was done, use GCP replicate snapshot function to copy a new vm
then
2) go back to first server, run node firstOrbitDbHost.js in folder "ipfs"
3) go to next server, run node PeerOrbitDb.js  in folder "ipfs"

After 2 server ran ok, then I replicate the 2nd server into 3rd server and run the 
node PeerOrbitDb.js  in folder "ipfs"

Third server failed.

After reading your comment, I changed the sequence
1) setup the node.js in a server
2) replicate the server in 1 into server 2 and server 3
3) deploy orbitdb library in server1, server 2 and server 3 separately in ipfs
4) deploy the 2 script separately in server1, server2 and server3
5) fire up the firstOrbitDbHost.js in server 1 and PeerOrbitDb.js  in the rest of servers

It works!!! even I shutdown the server 3 and restart or server 1 and restart ...they works as expected.

Thing ahead.... figure out how to package the script into docker container and make it works...
