### ISSUE TITLE
Remote database address on web demo is almost impossible to copy

### ISSUE THREAD

**Issue by ricardojmendez** [orbitdb/orbit-db#311]
This is a usability issue on Chrome, might not be on some other browsers. 

- Start the web demo
- Enter a database name and open for event log
- You'll see the continually updating results

![screen shot 2018-01-21 at 08 40 19](https://user-images.githubusercontent.com/31263/35192096-43158194-fe8b-11e7-9291-7f41b6d3e500.png)

- Try to select the event log address to open a remote database
- The JS keeps re-writing the DOM, including the element containing the address, making it almost impossible to time the copy action

It would be ideal to keep this particular element static and only update the ones below it, so that the user can more easily select it and test replication.

**Comment by haadcode** [comment]
Agreed @ricardojmendez! This is terrible UX atm. It happens because we refresh the whole "Results" part upon a query (whereas we should only update the results).

The code responsible for it is here: https://github.com/orbitdb/orbit-db/blob/master/examples/browser/example.js#L241 if anyone wants to improve it.

**Comment by haadcode** [comment]
This was fixed in #325 by @claus. Thanks everyone for making OrbitDB a little bit better! ❤️😄
