### ISSUE TITLE
Typescript Definition?

### ISSUE THREAD

**Issue by varcario** [orbitdb/orbit-db#347]
Are there any interests in creating a TypeScript definition for Angular Developers?

Typings Collaboration
https://github.com/typings/typings/issues/322

**Comment by haoliangyu** [comment]
I am also planning to use this library in an Angular project and would like to contribute.

**Comment by willemneal** [comment]
I just created a shell of type definitions here: https://github.com/willemneal/types-orbit-db

I am unsure what the best route is either a similar shell for each module within the orbit-db ecosystem or to just put everything in the one place.  For now, I think the best is to just place everything here.  The definitions for each docstore should be placed in the namespace section at the bottom.

**Comment by Stradivario** [comment]
Hello guys i am creating GraphQL Framework @gapi 
https://github.com/Stradivario/gapi you can check it out

Yesterday while i was typing some Orbit DB module which can be found here:
https://github.com/Stradivario/gapi-orbitdb i decided to create also typings for orbit db because they where missing.

Here are not finalized typings but they will be updated regular.
https://github.com/Stradivario/gapi-orbitdb/blob/master/development/gapi-orbitdb-injection.ts

**Comment by aphelionz** [comment]
Hey everybody, just want to call your attention to the typescript defs here as well https://github.com/orbitdb/orbit-db/issues/466

**Comment by aphelionz** [comment]
Pull request submitted https://github.com/orbitdb/orbit-db/pull/541
