### ISSUE TITLE
Permissions & Read Only Users?

### ISSUE THREAD

**Issue by balupton** [orbitdb/orbit-db#357]
Is it possible to create users on orbitdb, so some have write access, and some have read access

**Comment by balupton** [comment]
The use case for the database that I am wrestling with, is hundreds of gigabytes of cryptocurrency historical price data.

I want to have it so that a few authorised servers can keep the data updated by writing new data every minute. But then have everyone get read access to the database.

OrbitDB seems perfect as (unlike Couch and Cockroach) anyone who is querying the data is also replicating and sharing the data.

**Comment by adrprado** [comment]
You can check the [guide](https://github.com/orbitdb/orbit-db/blob/51b79745a7fd4a51b34c86120c749214a31af794/GUIDE.md#access-control). There is states this: "You can specify the peers that have write-access to a database. You can define a set of peers that can write to a database or allow anyone write to a database."

**Comment by balupton** [comment]
Yes but it also states:

> Note! OrbitDB currently supports only write-access and the keys of the writers need to be known when creating a database. That is, the access rights can't be changed after a database has been created. In the future we'll support read access control and dynamic access control in a way that access rights can be added and removed to a database at any point in time without changing the database address. At the moment, if access rights need to be changed, the address of the database will change.

Which makes it seem that only write access is currently implemented. That options are write access or no access. From what I can tell, read only access is a planned feature, but there was no issue about it yet.

**Comment by adrprado** [comment]
In fact, you have write access or read-only access.

When you create the database you need to set the users that'll have write access (you set it with a list of IDs or '*' to allow all users to write):

    const access = {
      write: ['*'],
    }
    const db = await orbitdb.docstore('sample-db', access);

BTW, issue #292 was opened requesting help on access rights improvement.

**Comment by aphelionz** [comment]
Thanks @balupton and @adrprado. It's awesome to see community members helping each other out. Essentially that is correct - all data are publicly readable due to the nature of IPFS, but OrbitDB _can_ manage write access for you - even dynamically in the latest release candidate, `orbit-db@rc2`

To secure the read-only data, you can use encryption so that it will appear as gibberish to those who don't have the decryption keys. We discuss this a bit in the [OrbitDB Field Manual](https://github.com/orbitdb/field-manual), so check it out and open an issue or PR there if you have more questions or if something doesn't make sense.
