### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by lukas2005** [orbitdb/orbit-db#372]
First: How well does OrbitDB handle VERY maybe even extremely large databases?
Can't give you an exact number currently but you can imagine a database of a similar size to Discord's (cause i'm making a very similar chat app)
(I'm planning on having one key-value database per guild, one key-value database per user and one feed database per channel)

Two: When will a better permission system get created?
This one is VERY important.
Cause limiting access to guild's database will be needed to avoid stuff like regular users changing the name of the guild etc.
And by better I mean dynamic permissions and more permission levels:
Read: those users can only read the database
Write: those users can both write and read
Delete: Read + Write + Deleting stuff
Admin: All previous + change permissions etc

Three: How can users export / import the OrbitDB identity? And is it a good idea to use it to identify them in the chat app or should I use IPFS Peer IDs?

Another one: Does orbitdb store data in IPFS? I mean can you retrieve it even if no DB peers are available

This one is a feature request: Custom access controllers. It could work this way:
```js
let access = function(name, operation, accesorId) {
// custom code return true if operation should be allowed
}

let DB = orbit.keyvalue("name", access);
```
I need this cause I want to have a main database where I store database addresses for each user / guild and I only want the person who added their entry to be able to modify it.
So i'd like to have that feature (unless you think there is a better way than to hold that large db of users and guilds)

**Comment by lukas2005** [comment]
Another question: In the feed database in the iterator method when I set the limit option to e. g. 10 will it be 10 first or last entries?

**Comment by coyotespike** [comment]
(1) I don't know how OrbitDB handles extremely large databases. Because under the hood Orbit uses a log to build each database, and the log grows without bound, eventually we will have to worry about this.
(2) Dynamic permissions are under active development and will come ASAP!
(3) By identity, do you mean the keystore key pair? As part of dynamic permissions, working on a way to have a local keypair and an Ethereum keypair. The Ethereum public key lives in a smart contract to serve as identity. So we don't have to export the local Orbit keypair.
(4) Custom access controllers are at the heart of the dynamic permissions development :+1:
(5) I think it's last 10, no?

**Comment by lukas2005** [comment]
thanks 👍
