### ISSUE TITLE
[question] How is address of node sufficient for communication

### ISSUE THREAD

**Issue by CaptainQuark** [orbitdb/orbit-db#440]
Hi,

OrbitDB looks really great, my team is currently evaluating its use in a medical environment. After reading the docs + issues, I still don't know how a node's address (orbit-db-protocol/hash/db-name) is sufficient to be used as address for a remote db, even more as communication isn't required to be in the same local network (which is insanely great, btw). If a kind of middleware/broker is used, it would be really great to know more about it - it's the only detail I couldn't find in the docs. 

Thanks in advance, and keep up the great work!
Tom

**Comment by mistakia** [comment]
It depends on your IPFS setup — The IPFS network is used to store the data and thus content-routing and communication relies on how you setup and use IPFS. For instance, DHT content-routing, a big part of connectivity magic, is not fully operational in the JS implementation but working in the Go implementation. Thus, in the JS implementation its helpful to [configure a shared signalling server](https://ipfs.io/ipfs/QmY2LufsW3v6AfxTTkp6SGqDGa5AeJhSZXH8RSsdiao4Ds/) so that your nodes can find each other.

**Brief overview of OrbitDBAddress as it relates to IPFS:**
The *magic* and crux of an OrbitDBAddress is the hash part, which is an IPFS [Multihash](https://github.com/multiformats/multihash). The hash is used to retrieve a [database manifest](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#manifest), and subsequently an access controller. Both of which are objects stored on IPFS which is a content-addressable storage system. The hash in the OrbitDBAddress points to the database manifest and inside the database manifest is another hash that points to the Access Controller.

To replicate the entries in the database, the OrbitDBAddress is used as a topic on IPFS PubSub to exchange [heads](https://github.com/orbitdb/ipfs-log/blob/master/API.md#heads) which can be used to retrieve the rest of the entries as each entry links to the previous one, see [IPFS-Log](https://github.com/orbitdb/ipfs-log).

**Comment by CaptainQuark** [comment]
Thanks, that's one hell of an answer 😁, exactly what I was looking for. I seriously recommend copy/pasting your explanation as a paragraph into the docs.

Again, thx for the great support!

**Comment by RichardLitt** [comment]
@CaptainQuark Thanks for the kind words! 

@mistakia Want to PR the answer into the docs? If not, I (or @CaptainQuark, maybe) would be happy to.

**Comment by mistakia** [comment]
@RichardLitt go for it! as I'm unsure of the best course of action but I'm more than happy to help out along the way.

This could fit into the GUIDE but I think perhaps we should start a separate FAQs doc to aggregate many of the general & helpful questions answered in the issues.
