### ISSUE TITLE
Add roadmap summary to OrbitDB README

### ISSUE THREAD

**Issue by sirfumblestone** [orbitdb/orbit-db#526]
Today the roadmap information is "hidden" to [Waffle](https://waffle.io/orbitdb/orbit-db) and is only briefly mentioned in README's [Contribution section](https://github.com/orbitdb/orbit-db#contributing). Also Waffle tends to be both busy and somewhat complex for an untrained eye. 

I think it would be beneficial for both the existing community and especially to new people who come across orbit-db to see a simple list of what major features/fixes (e.g. [dynamic access control](https://github.com/orbitdb/orbit-db/pull/495)) are under development right now.

Does this make sense?

**Comment by RichardLitt** [comment]
The waffle board works across repositories, but I don't know that it has been updated especially in a while - I know that I haven't been using it, which isn't a good sign in general. A clearer way of seeing current issues would be good. Right now, the best way to do this is the jump on the call. 

@haadcode: you've mentioned the waffle board before as something you want to bring back. Am I right in thinking that?

**Comment by haadcode** [comment]
In the past we used Waffle (for Orbit Chat) to have display a) what's currently being worked on and b) what's on the roadmap. I think it was great and would love to start using it (as part of the "official process") for OrbitDB too.

Waffle doesn't need manual updating in any way, it's [always up to date](https://waffle.io/orbitdb/orbit-db). What it does need is properly configure the labels to match the board columns (which we never did for this repo, but have a tool to automate it across it org in https://github.com/haadcode/labels-and-milestones).

That all said, the Waffle board right now is much more a real-time view to the roadmap as opposed "list of couple of main things". However, proper process/structuring of the issues in GH, can do that in Waffle too (eg. have an issue for each "main thing" and label them so that it's clear they're "bigger things" than individual PRs).

All in all, I personally would want to automate it as much as possible in order to avoid manually updating READMEs or other files to reflect the current status.

**Comment by RichardLitt** [comment]
> However, proper process/structuring of the issues in GH, can do that in Waffle too (eg. have an issue for each "main thing" and label them so that it's clear they're "bigger things" than individual PRs).

We could also have an issue for each quarter, which refers to the other main issues we're working on. We could pin this issue to the top of the repo. That's fairly minimal in the work involved, and it could be used as a 'subscribe to updates' issue we could post to after each call. What do you think?

**Comment by MTonomy-Nchinda-Nchinda** [comment]
waffle.io no longer exists

**Comment by RichardLitt** [comment]
You're right, and we've also turned it off. We'll post another issue about our long-term plans sometime in the fall; for now, we're focusing on the next release. See https://github.com/orbitdb/orbit-db/issues/585. Instead of adding this to the README, we've started pinning it as an issue (it's the top issue), so I am going to close this issue as no longer needed. Thanks for pinging, @MTonomy-Nchinda-Nchinda
