### ISSUE TITLE
Add links/badges to matrix and discord chats

### ISSUE THREAD

**Issue by swedneck** [orbitdb/orbit-db#690]
https://riot.permaweb.io/#/room/#orbitdb:permaweb.io
and
https://discord.gg/cscuf5T

These are both bridged to the gitter chat, via matrix.

**Comment by RichardLitt** [comment]
Having a single point of entry makes it easier to encourage people to join the chatroom. Instead of saying "Join us on all of the things", "join us on the Gitter" encourages a single use case that also then allows us to do other things - for instance, have the orbitdb-dev channel on Gitter. I'm not sure adding bridges will help people talk easier.

That having been said (and I'm not certain about it - it's just a gut feeling) - I think there is value to saying that the bridges exist. Why don't we add links in the Contribute section here and in Welcome? What do you think, @swedneck?

**Comment by aphelionz** [comment]
I disagree, I think the bridges are really helpful and we should try to be agnostic to which chat client people want to use. I for one lament the fact that I can't keep up with what's going on on Discord and Matrix, particularly when it comes to the community. I can really only keep up with a couple, Gitter being one. I've also seen an interacted with folks over the bridge on Matrix while I was on Gitter.

So, thank you @swedneck for the bridges!

**Comment by RichardLitt** [comment]
Well then. Let's be agnostic. 

@swedneck Want to PR badges? I'm happy to add them, too.

**Comment by swedneck** [comment]
I can try!

**Comment by RichardLitt** [comment]
@swedneck The Discord badge appears to be broken according to someone on Gitter. Any ideas?

**Comment by vuldin** [comment]
Also, it seems the matrix badge is no longer working.

**Comment by swedneck** [comment]
sorry, didn't see this until the latest message, i'll make PRs to fix this.

**Comment by mattsilv** [comment]
Is there still a discord channel for orbitdb? when I click the discord invite link it says it's invalid.
