### ISSUE TITLE
OrbitDB Roadmap for the rest of 2019

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbit-db#719]
:wave: Hey everyone. Now that [0.22.0](https://github.com/orbitdb/orbit-db/blob/master/CHANGELOG.md#v0220) is launched, for the next two months, the main OrbitDB maintainers are committing to working on a few things: bug fixes, performance upgrades and minor improvements!

These PRs are currently in the works:

- **Fetching entries**: The structure of entries is changing to include references to entries in distances in powers of two, allowing better loading and parallelization of entry-fetching. Cf. https://github.com/orbitdb/ipfs-log/pull/275
- **Identity-management**: [identity-provider](https://github.com/orbitdb/orbit-db-identity-provider) will maintain a cache of identities to improve verification (thanks [@oed](https://github.com/oed)) and each orbitdb instance will have an identity-provider to manage and verify identities. Cf. https://github.com/orbitdb/orbit-db-identity-provider/pull/49, https://github.com/orbitdb/orbit-db/pull/697

OrbitDB is an open source project; it's right there in the MIT license. We also hope to be a welcoming project - anyone is free to work on any part of it, and, as people show up, we're happy to have them join the organization, take control of their domains and repositories, and [become maintainers](https://github.com/orbitdb/welcome/blob/master/contributing.md#becoming-a-maintainer) on OrbitDB itself.

With that in mind, for the next few months, the Haja Networks maintainers are also working very hard on another, similar project - [@ambientsprotocol](https://github.com/ambientsprotocol). Our goal is to build an open source protocol for distributed computation on a decentralized network. Think dApps, but without the blockchain; think IPFS and OrbitDB, but language-agnostic, and for code, not just databases. We are around to answer questions, help with bug fixes, and merge PRs. However, our top priority right now is getting @ambientsprotocol out. If you're interested in helping us, please get in touch!

If you have any urgent needs for OrbitDB, jump on [Gitter](https://gitter.im/orbitdb/Lobby) or let us know. If you need support, definitely jump on Gitter or take another look at the [OrbitDB Field Manual](https://github.com/orbitdb/field-manual). If you find a bug or need a feature, open an issue in the relevant repository. We'll take a look.

See you out there!

**Comment by KrishnaPG** [comment]
Sorry, but for some reason, that sounds more like a _good-bye_ note, and that is concerning. Should we be worried about the future of OrbitDB?

**Comment by RichardLitt** [comment]
Thanks for asking, @KrishnaPG. ❤️ 

If it sounds that way, it's my bad. This isn't a goodbye note. As I said, we're working on the next release, and we're actively working to resolve issues and to merge pull requests. However, I can see why you would think this. Our main emphasis is somewhere else _for the time being_ - the Haja Networks team is working primarily on @ambientsprotocol for the time being. We don't view this as a switch but as a continuation of this work. Ambients will _rely_ on OrbitDB. So, in short, we're not going anywhere, and the future is bright. :slightly_smiling_face:

**Comment by KrishnaPG** [comment]
Thank you @RichardLitt 

Orbit-DB is one of the primary contenders in the distributed DBs currently, the other ones being Gun and its peers. Being built on IPFS/Libp2p, however, means that Orbit has scope for some unique possibilities.

A system built on top of Orbit, such as @ambientsprotocol, then, I hope, becomes a feedback loop for Orbit DB's improvement in the long run. Looking forward to trying out Ambients in the coming days. 

In the earlier days, we had MPI for distributed computing across CPUs and recently Hadoop style of frameworks (moving computation to data) followed later by Lambda (serverless) functions. Not to mention the GPU based parallel processing with OpenCL, and the recent likes of [AresDB](https://github.com/uber/aresdb) (GPU-powered real-time analytics storage and query engine based on CUDA). Hope to see a detailed comparison of Ambients with each of such earlier frameworks so that we can understand the use-cases where Ambients fits nicely in the solution design, there by probably start recommending to our customers where there is a fit.

**Comment by aphelionz** [comment]
Closing this for now as a new roadmap issue is pending :+1:
