### ISSUE TITLE
Access controller invoked when DB is loaded from disk?

### ISSUE THREAD

**Issue by christroutner** [orbitdb/orbit-db#874]
I'm creating a prototype for a pay-to-write database. I'm attempting to create a custom [Access Controller](https://github.com/orbitdb/orbit-db-access-controllers) for a key-value store. The 'key' part is a transaction ID (TXID) on the Bitcoin Cash (BCH) blockchain. The idea is to create a pay-to-write database, where anyone can write to the database if they prove that they burned a token to pay for it.

The Access Controller seems to be working well. However, when the database is loaded from disk, each entry is passed through the `canAppend()` method of the Access Controller. Since the Access Controller makes network calls to verify the TXID, it can be quite slow.

The slow connection doesn't matter for a write, but it's impractical to have a database validate each entry upon starting the application and loading the saved DB data from disk. But maybe I'm making a silly coding mistake?

- [Here is my custom access controller](https://github.com/Permissionless-Software-Foundation/pay-to-write-orbitdb/blob/master/lib/pay-to-write-access-controller.js)
- [Here is an example file for writing to the database](https://github.com/Permissionless-Software-Foundation/pay-to-write-orbitdb/blob/master/examples/write-to-db.js)
- [Here is an example file for reading from the database](https://github.com/Permissionless-Software-Foundation/pay-to-write-orbitdb/blob/master/examples/read-db.js). This last file will re-create the problem discussed in this Issue.

It doesn't seem necessary to validate each entry when loaded from disk. Am I doing something wrong? Or is this by design?

Any suggestions on how I could skip the validation of database entries when loading the DB from disk?

**Comment by tabcat** [comment]
> It doesn't seem necessary to validate each entry when loaded from disk. Am I doing something wrong? Or is this by design?

The short answer to this is that currently the set of validated entries is not persisted. Entries are loaded from ipfs by traversing from persisted head entry hashes.

> Any suggestions on how I could skip the validation of database entries when loading the DB from disk?

You need a way to know which entries have been previously validated and skip those. This is mainly useful for memoizing data that will not change like digital signatures. In your case with BCH, since it is a blockchain which provide some immutability wrt to variables; you could call an entry ~permanently valid after N many blocks.

I'm not sure what the best thing to do is. I would try either tracking all missing/only referenced entries + invalid/not-validated entries, or all valid entries, or all valid entries referencing at least 1 missing/invalid/not-validated entries.
With the third option, I think lookups to BCH are needed for any entries referenced by matching entries minus already loaded entries.

**Comment by christroutner** [comment]
Thank you for the suggestions @tabcat!

One idea I had to overcome this issue would be to run a local database, like MongoDB or LevelDB. After an entry is validated, it would be added to the local database. On startup, the `canAppend()` method would check to see if each entry exists in the local database, which would indicate that it has already been validated. New entries (which wouldn't exist in the local database) would be validated against the blockchain directly.

However, what is to prevent another instance of the same database from spoofing this check? Does the hash of the OrbitDB database include the `canAppend()` code or something?

**Comment by phillmac** [comment]
The orbitdb hash includes the hash of the access controller rules. You can
check it by using `ipfs dag get` to find the access controller hash and
then dag get that.
If one node meddles with their local copy it should be a non-issue because
the access controller should reject any tampered entries when it tries to
replicate thrm ti any other node.

**Comment by christroutner** [comment]
Beautiful.

That's exactly the answer I was hoping for. Thanks for the tip, I'll give that a go, to try and find the hash.
